# Generated by Django 5.0.4 on 2024-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_twitteruser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='banner_image',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
