# Generated by Django 5.0.4 on 2024-05-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_twitteruser_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
