# Generated by Django 5.0.4 on 2024-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_twitteruser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
