# Generated by Django 5.0.4 on 2024-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
