# Generated by Django 5.0.4 on 2024-05-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_tweet_is_comment_alter_tweet_content_and_more'),
        ('users', '0005_alter_twitteruser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.twitteruser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.twitteruser'),
        ),
    ]
