# Generated by Django 5.0.4 on 2024-05-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_tweet_likes_alter_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='parent',
            new_name='replied_tweet',
        ),
    ]
