# Generated by Django 5.0.4 on 2024-05-12 16:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_parent_tweet_replied_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
